"use client"

import LeadForm from '@/app/components/LeadForm'
import WhatWeDoLayout from '@/app/components/WhatWeDoLayout'
import Image from 'next/image'
import { title } from 'process'
import React from 'react'

const SearchEngineOptimization = () => {
    const client = [
        { id: 1, no: 421, desc: "Happy Clients" },
        { id: 2, no: 47, desc: "Mobile Apps" },
        { id: 3, no: 26, desc: "Years Exp" }

    ]

    const ApplicationDev = [
        { id: 1, title: "BUSINESS APPS", desc: "Digital | Mobile | CLM Experiental" },
        { id: 2, title: "E-COMM APPS.", desc: "Scientific Storytelling / MLR Standards | Identity" },
        { id: 4, title: "EDUCATION APPS.", desc: "Scientific Storytelling / MLR Standards | Identity" },
        { id: 3, title: "SOCIAL NET APPS.", desc: "Health & Fitness | Lifestyle | Productivity" },
        { id: 5, title: "ENTERTAIN APPS.", desc: "Tailored Solutions | Business Needs | User Experience" },
        { id: 6, title: "E-BOOKS APPS", desc: "Digital | Mobile | CLM Experiental" },
    ]
    return (
        <div>
            <WhatWeDoLayout children="SEARCH ENGINE OPTIMIZATION" >
            </WhatWeDoLayout>

            <section className='max-w-6xl mx-auto'>
                <div className='px-4 py-16'>
                    <p>We are a mobile application development outsourcing company based in India. We have designed thousands of custom mobile apps that have delighted and made life easy for millions of people. From startups to digital agencies and large enterprises, our custom mobile app development company has partnered with hundreds of clients to deliver feature rich mobile apps.
                    </p>
                </div>
            </section>

            <section className="bg-black py-16 md:py-24">
                <div className="max-w-7xl mx-auto px-4 sm:px-6">
                    <div className="flex flex-col lg:flex-row items-center gap-12">

                        <div className="w-full lg:w-1/2 text-white">
                            <h2 className="text-3xl md:text-4xl font-bold mb-6">
                                LET&apos;S FIND OUT answer with some mind-boggling stats:
                            </h2>

                            <p className="text-red-500 mb-6">
                                1 in 5 people in the world own a smartphone
                                There are 224 million monthly active app users in the US
                                US adults spend an average of 2 hours and 51 minutes a day using mobile devices
                                79% of smartphone owners use apps nearly every day
                                42% of all mobile sales generated by leading 500 merchants came from mobile apps
                                Mobile ads perform 4-5 times better than online ads
                                62% of smartphone users are "ok with 15-30 second ads" in exchange for video content
                            </p>

                            {/* <ul className="list-disc pl-6 space-y-2 text-gray-200">
                <li>We provide impeccable iPhone application development services on our platform.</li>
                <li>With our iPad application development services, you can take your business to new heights.</li>
                <li>Ring Scale Mediamedia is also capable of designing applications for your Apple TV and other such devices.</li>
                <li>Apart from this, we are also expert in designing captivating applications for Apple Watch.</li>
              </ul> */}
                        </div>

                        <div className="w-full lg:w-1/4 text-center">
                            <h3 className="text-yellow-400 text-xl md:text-2xl font-semibold">
                                Do You Actually Need a New Mobile App?
                            </h3>
                        </div>

                        <div className="w-full lg:w-1/4 flex justify-center">
                            <Image
                                src="/whatwedo/phoneimg.png"
                                alt="iPhone iPad"
                                width={450}
                                height={450}
                                className="object-contain"
                            />
                        </div>

                    </div>
                </div>
            </section>

            <section className="max-w-6xl mx-auto px-4 py-16">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
                    <div>
                        <h1 className="font-bold text-3xl md:text-4xl leading-tight mb-6">
                            OUR MOBILE APP DEVELOPMENT SERVICE
                        </h1>

                        <p className="text-gray-600 mb-4 leading-relaxed">
                            Our offshore mobile app development company provides end-to-end custom mobile app development services. Some of our services include:

                        </p>

                        <p className="text-gray-600 leading-relaxed">
                            Our offshore mobile app development company provides end-to-end custom mobile app development services. Some of our services include Our offshore mobile app development company provides end-to-end custom mobile app development services. Some of our services include. Our offshore mobile app development company provides end-to-end custom mobile app development services. Some of our services include..

                        </p>
                    </div>

                    <div className="flex justify-center">
                        <Image
                            src="/whatwedo/iphone-ios.jpg"
                            alt="iOS Development"
                            width={450}
                            height={450}
                            className="rounded-xl object-cover"
                        />
                    </div>

                </div>
            </section>

            <section className='bg-[#778DDF] h-auto w-full'>
                <div className='max-w-6xl mx-auto px-4 py-16 text-white grid grid-cols-1 md:grid-cols-3 gap-8'>
                    {client.map((cli) => (
                        <div key={cli.id} className='text-center mb-8'>
                            <div className='bg-white h-0.5 mb-10'></div>
                            <h2 className='text-4xl md:text-5xl font-bold'>{cli.no}</h2>
                            <p className='text-2xl font-bold  mt-2'>{cli.desc}</p>
                            <div className='bg-white h-0.5 mt-10'></div>

                        </div>
                    ))}
                </div>
            </section>

            <section className="max-w-6xl mx-auto px-4 py-20">
                <div className="text-center">
                    <h1 className="text-3xl md:text-4xl font-extrabold text-gray-900 leading-tight">
                        OUR MOBILE APP <br />
                        <span className="text-blue-600">DEVELOPMENT EXPERTISE</span>
                    </h1>

                    <p className="mt-4 max-w-2xl mx-auto text-gray-600 text-lg">
                        Being one of the best mobile app development companies in India, we cater to a wide array of business verticals. Some of our verticals include:</p>

                    <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mt-14">
                        {ApplicationDev.map((app) => (
                            <div
                                key={app.id}
                                className="group relative bg-white border border-gray-200 rounded-2xl p-8 shadow-sm 
                     hover:shadow-2xl hover:-translate-y-2 transition-all duration-300"
                            >

                                <div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-blue-500 to-purple-500 rounded-t-2xl opacity-0 group-hover:opacity-100 transition" />

                                <h2 className="text-xl font-semibold text-gray-900 mb-3">
                                    {app.title}
                                </h2>

                                <p className="text-gray-600 leading-relaxed">
                                    {app.desc}
                                </p>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            <section className="relative bg-black text-white overflow-hidden py-24">
                <h2 className="text-center text-3xl md:text-5xl font-extrabold tracking-wide">
                    WE DELIVER AWESOME <br />
                    <span>MOBILE APPLICATION</span>
                </h2>


                <div className="max-w-6xl mx-auto px-6 mt-20 grid grid-cols-1 lg:grid-cols-3 items-center gap-12">

                    <div className="space-y-6 text-gray-300 text-sm md:text-base leading-relaxed">
                        <p>
                            Highly scalable and robust mobile apps from experienced team of 40+ mobile app developers who've worked on 300+ apps so far.
                        </p>

                        <p>
                            Cross-device functionality across all smartphone devices- compatible with all versions of smartphones.
                        </p>

                        <p>
                            Assigning the work to right team dedicated to your project to reduce complexity and enhance productivity.
                        </p>
                    </div>


                    <div className="flex justify-center relative">
                        <img
                            src="/whatwedo/b.png"
                            alt="Brand Logo"
                            className="w-48 md:w-64 lg:w-72 drop-shadow-[0_0_30px_rgba(255,0,100,0.4)]"
                        />
                    </div>


                    <div className="space-y-6 text-gray-300 text-sm md:text-base leading-relaxed">
                        <p>
                            Highly scalable and robust mobile apps from experienced team of 40+ mobile app developers who've worked on 300+ apps so far.
                        </p>

                        <p>
                            Cross-device functionality across all smartphone devices- compatible with all versions of smartphones.
                        </p>

                        <p>
                            Assigning the work to right team dedicated to your project to reduce complexity and enhance productivity.
                        </p>
                    </div>
                </div>


                <div className="text-center mt-20">
                    <h3 className="text-xl md:text-2xl font-semibold">
                        Have Queries? We are happy to help you!
                    </h3>
                    <p className="text-gray-400 mt-2">
                        Find the relevant answers
                    </p>
                </div>


                <div className="absolute left-6 top-1/2 -translate-y-1/2 h-64 w-[2px] bg-gradient-to-b from-pink-500 to-transparent" />
                <div className="absolute right-6 top-1/2 -translate-y-1/2 h-64 w-[2px] bg-gradient-to-b from-pink-500 to-transparent" />
            </section>

            <section className="max-w-6xl mx-auto px-4 py-20">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">

                    {/* Left Content */}
                    <div>
                        <Image
                            src="/whatwedo/advantage.png"
                            alt="Our Advantage"
                            width={420}
                            height={420}
                            className="object-contain mb-6"
                        />

                        <h2 className="text-2xl md:text-3xl font-bold text-gray-900 leading-snug">
                            We are counted among best mobile development companies in India
                        </h2>

                        <p className="mt-4 text-gray-600 leading-relaxed max-w-lg">
                            owing to our ethical business practices and transparent dealing. Here are some of our USPs:
                        </p>

                        <button className="mt-6 inline-flex items-center px-6 py-3 bg-blue-600 text-white font-semibold rounded-lg shadow-md hover:bg-blue-700 transition">
                            Get Started Today
                        </button>
                    </div>

                    {/* Right Image */}
                    <div className="flex justify-center md:justify-end">
                        <div className="relative bg-white p-6 shadow-lg">
                            <Image
                                src="/whatwedo/moneybck.png"
                                alt="Money Back Guarantee"
                                width={220}
                                height={220}
                                className="object-contain"
                            />

                        </div>
                    </div>

                </div>
            </section>
            <section className='bg-[#292A30] h-28 w-full'>
                <p className="mt-4 text-center text-2xl font-bold text-white py-6">
                    100% money back guarantee, <br />
                    if not satisfied
                </p>

            </section>
<section>
    <LeadForm />
</section>
        </div>
    )
}


export default SearchEngineOptimization